# Default values for jats-validator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

images:
  tag: latest
  pullPolicy: Always
  repository: elifesciences/jats-validator

nameOverride: ""
fullnameOverride: ""

service:
  port: 80