apiVersion: v1
kind: Service
metadata:
  name: {{ include "jats-validator.fullname" . }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ include "jats-validator.fullname" . }}.elifesciences.net
  labels:
    app.kubernetes.io/name: {{ include "jats-validator.name" . }}
    helm.sh/chart: {{ include "jats-validator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "jats-validator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}